name: 'Chess.com Games & Stats'
description: 'Automatically update your README.md with Chess.com games and stats - fully customizable'
author: 'Leonardo Montini'

inputs:
  CHESS_USERNAME:
    description: 'Your Chess.com username'
    default: 'hikaru'
    required: true
  COMMIT_MSG:
    description: "Commit message used while committing to the repo"
    default: "Update README with your chess games"
    required: false
  GAMES_SIZE:
    description: "How many games to load"
    default: "10"
    required: false
  SHOW_DATE:
    description: "Toggle the Date column"
    default: "true"
    required: false
  FILE_NAME:
    description: "Define a specific file in your repo"
    default: "README.md"
    required: false
    
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'green'
